import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DateAdapter,
  MAT_DATE_LOCALE,
  MatButtonModule,
  MatCardModule,
  MatDatepickerModule,
  MatDialogModule,
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatNativeDateModule,
  MatPaginatorIntl,
  MatPaginatorModule,
  MatTableModule,
  MatToolbarModule,
  MatTooltipModule
} from '@angular/material';
import { MatPaginatorIntlSv } from './mat-paginator-intl-sv';
import { SwedishDateAdapter } from '../angular/swedish-date-adapter';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatButtonModule,
    MatCardModule,
    MatToolbarModule,
    MatListModule,
    // MatCheckboxModule,
    // MatCheckboxModule,
    MatInputModule,
    // MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatFormFieldModule,
    // MatRadioModule,
    // MatSelectModule,
    // MatSliderModule,
    // MatSlideToggleModule,
    // MatMenuModule,
    // MatSidenavModule,
    // MatGridListModule,
    // MatStepperModule,
    // MatTabsModule,
    // MatExpansionModule,
    // MatButtonToggleModule,
    // MatChipsModule,
    MatIconModule,
    // MatProgressSpinnerModule,
    // MatProgressBarModule,
    MatDialogModule,
    // MatTooltipModule,
    // MatSnackBarModule,
    MatTableModule,
    // MatSortModule,
    MatPaginatorModule,
    MatTooltipModule
  ],
  exports: [
    MatButtonModule,
    MatCardModule,
    MatToolbarModule,
    MatListModule,
    // MatCheckboxModule,
    // MatCheckboxModule,
    MatButtonModule,
    MatInputModule,
    // MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatFormFieldModule,
    // MatRadioModule,
    // MatSelectModule,
    // MatSliderModule,
    // MatSlideToggleModule,
    // MatMenuModule,
    // MatSidenavModule,
    // MatGridListModule,
    // MatStepperModule,
    // MatTabsModule,
    // MatExpansionModule,
    // MatButtonToggleModule,
    // MatChipsModule,
    MatIconModule,
    // MatProgressSpinnerModule,
    // MatProgressBarModule,
    MatDialogModule,
    // MatTooltipModule,
    // MatSnackBarModule,
    MatTableModule,
    // MatSortModule,
    MatPaginatorModule,
    MatTooltipModule
  ],
  providers: [
    {provide: MatPaginatorIntl, useClass: MatPaginatorIntlSv},
    {provide: DateAdapter, useClass: SwedishDateAdapter},
    {provide: MAT_DATE_LOCALE, useValue: 'sv-SE'},
  ]
})
export class MaterialModule {
}
