import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatCardModule,
  MatToolbarModule,
  MatListModule,
  // MatCheckboxModule,
  // MatButtonModule,
  MatInputModule,
  // MatAutocompleteModule,
  // MatDatepickerModule,
  MatFormFieldModule,
  // MatRadioModule,
  // MatSelectModule,
  // MatSliderModule,
  // MatSlideToggleModule,
  // MatMenuModule,
  // MatSidenavModule,
  // MatGridListModule,
  // MatStepperModule,
  // MatTabsModule,
  // MatExpansionModule,
  // MatButtonToggleModule,
  // MatChipsModule,
  MatIconModule,
  // MatProgressSpinnerModule,
  // MatProgressBarModule,
  MatDialogModule,
  // MatTooltipModule,
  // MatSnackBarModule,
  MatTableModule,
  // MatSortModule,
  MatPaginatorModule, MatPaginatorIntl
} from '@angular/material';
import { MatPaginatorIntlSv } from './mat-paginator-intl-sv';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatCardModule,
    MatToolbarModule,
    MatListModule,
    // MatCheckboxModule,
    // MatCheckboxModule,
    // MatButtonModule,
    MatInputModule,
    // MatAutocompleteModule,
    // MatDatepickerModule,
    MatFormFieldModule,
    // MatRadioModule,
    // MatSelectModule,
    // MatSliderModule,
    // MatSlideToggleModule,
    // MatMenuModule,
    // MatSidenavModule,
    // MatGridListModule,
    // MatStepperModule,
    // MatTabsModule,
    // MatExpansionModule,
    // MatButtonToggleModule,
    // MatChipsModule,
    MatIconModule,
    // MatProgressSpinnerModule,
    // MatProgressBarModule,
    MatDialogModule,
    // MatTooltipModule,
    // MatSnackBarModule,
    MatTableModule,
    // MatSortModule,
    MatPaginatorModule
  ],
  exports: [
    MatCardModule,
    MatToolbarModule,
    MatListModule,
    // MatCheckboxModule,
    // MatCheckboxModule,
    // MatButtonModule,
    MatInputModule,
    // MatAutocompleteModule,
    // MatDatepickerModule,
    MatFormFieldModule,
    // MatRadioModule,
    // MatSelectModule,
    // MatSliderModule,
    // MatSlideToggleModule,
    // MatMenuModule,
    // MatSidenavModule,
    // MatGridListModule,
    // MatStepperModule,
    // MatTabsModule,
    // MatExpansionModule,
    // MatButtonToggleModule,
    // MatChipsModule,
    MatIconModule,
    // MatProgressSpinnerModule,
    // MatProgressBarModule,
    MatDialogModule,
    // MatTooltipModule,
    // MatSnackBarModule,
    MatTableModule,
    // MatSortModule,
    MatPaginatorModule
  ],
  providers: [
    {provide: MatPaginatorIntl, useClass: MatPaginatorIntlSv}
  ]
})
export class MaterialModule {
}
